### ISSUE TITLE
Long waiting of the "healthy" status

### ISSUE THREAD

**Issue by andrey-thm** [axllent/spamassassin#3]
It takes too much time for waiting for healthy status of this container. It would be great to change the default setting to something shorter, e.g.:

```
HEALTHCHECK --interval=1s --timeout=1s --retries=15 --start-period=15s --start-interval=1s \
    CMD netstat -ltn | grep -c 783
```

**Comment by axllent** [comment]
Unfortunately `--start_interval` is not a globally-supported Docker command ~ depending on what docker port one is using (for instance I'm using `docker.io` which does not support that). I'm also a bit hesitant to run the check every second (by default) as that seems quite excessive. Would `--interval=5s --start-period=15s --timeout=1s` work better for you? 

On a side note, I'm assuming you do know that you also can set your own healthcheck command when you start a Docker container?

**Comment by andrey-thm** [comment]
It is just netstat and grep, it cost nothint, it it why I prefer to save my time waiting for the container to be ready and set 1s.

But it is up to you, I can always override it in my in my setup. I just wanted to highlight that 1 minute waiting is too long.

**Comment by axllent** [comment]
Point noted, and I agree with the 1m interval being too high! I have reduced it to a 5s interval. Hopefully this solves your delay issue?
